-- 코드를 입력하세요
SELECT 
A.CAR_ID, 
A.CAR_TYPE,
A.DAILY_FEE*30*(100-C.DISCOUNT_RATE)/100 FEE
FROM CAR_RENTAL_COMPANY_CAR A, 
(SELECT CAR_ID, MAX(END_DATE) END_DATE
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 GROUP BY CAR_ID) B, CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
WHERE A.CAR_ID = B.CAR_ID
AND A.CAR_TYPE = C.CAR_TYPE
AND C.DURATION_TYPE = '30일 이상'
AND A.CAR_TYPE IN('세단', 'SUV')
AND A.DAILY_FEE*30*(100-C.DISCOUNT_RATE)/100 BETWEEN 500000 AND 2000000
AND B.END_DATE < TO_DATE(20221101, 'YYYY-MM-DD')
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC