-- 코드를 입력하세요
SELECT R.LV, NVL(E.CNT,0)
FROM
    (SELECT TO_CHAR(DATETIME, 'HH24') HOUR, COUNT(*) CNT
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'HH24'))E,
    (SELECT (LEVEL-1)LV 
    FROM DUAL 
    CONNECT BY LEVEL <= 24)R
WHERE
    R.LV = E.HOUR(+)
ORDER BY
    R.LV