-- 코드를 입력하세요
SELECT      A.BOOK_ID
        ,   (SELECT AUTHOR_NAME FROM AUTHOR X WHERE X.AUTHOR_ID = A.AUTHOR_ID) AUTHOR_NAME
        ,   TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD') PUBLISHED_DATE
FROM        BOOK    A
WHERE       1=1
            AND A.CATEGORY = '경제'
ORDER BY 3 ASC